name: GitHub Profile Summary Cards

on:
  schedule: # execute every 24 hours
    - cron: "* */24 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate profile summary cards
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Generate cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          USERNAME: OcatZ0  # Replace with your GitHub username
          UTC_OFFSET: 7     # Replace with your timezone offset (e.g., +7 for Jakarta)
